# This is a basic workflow to help you get started with Actions

name: Run/Deploy website (muarachmann.com)

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-tests:
    strategy:
      matrix:
        go-version: [1.12]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
        GOPATH: /__w/muarachmann/go/

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/muarachmann/go-cloud-build

    - name: Test and get Go modules
      run: |
        sudo go get -u github.com/golang/glog
        sudo go get -u golang.org/x/net/context
        sudo go get -u golang.org/x/net/context/ctxhttp
        sudo go get -u github.com/golang/protobuf/proto
        sudo go get -u github.com/golang/protobuf/protoc-gen-go
        sudo go get -u github.com/gorilla/mux
        sudo go get -u github.com/golang/glog
        sudo go get -u github.com/gorilla/sessions
        sudo go test -cover $(go list ./... | grep -v /vendor/)

    - name: Run go project
      run: go run main.go
