# This is a basic workflow to help you get started with Actions

name: Run/Deploy website (muarachmann.com)

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-tests:
    strategy:
      matrix:
        go-version: [1.12]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Install & Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Test & Get packages
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        go get -u github.com/golang/glog
        go get -u github.com/gorilla/mux
        go get -u github.com/gorilla/sessions  
        go get -u github.com/muarachmann/muarachmann.com/app/controllers
        go get -u github.com/muarachmann/muarachmann.com/app/common
     
    - name: Test project
      run: go test    
      
    - name: Build project
      run: go build
